version: '3.9'

services:

  blog-db:
    image: mongo:latest
    container_name: blog-db
    restart: always
    networks:
      - app-network
    ports:
      - "27017:27017"
    volumes:
      - blog-db-data:/data/db


  blog-service:
    build:
      context: ./blog-service
      dockerfile: Dockerfile
    container_name: blog-service
    restart: on-failure
    depends_on:
      - blog-db
    networks:
      - app-network
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://blog-db:27017/blog_db
      SERVER_PORT: 8082
      UPLOAD_DIR: /app/uploads
      GRPC_CLIENT_FOLLOWER_SERVICE_ADDRESS: static://follower-service:5001
      GRPC_CLIENT_FOLLOWER_SERVICE_NEGOTIATION_TYPE: plaintext
    volumes:
      - ./blog-service/uploads:/app/uploads


  stakeholders-db:
    image: postgres:15
    container_name: stakeholders-db
    restart: always
    networks:
      - app-network
    environment:
      POSTGRES_DB: stakeholdersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - stakeholders-db-data:/var/lib/postgresql/data


  stakeholders-service:
    build:
      context: ./stakeholders-service
      dockerfile: Dockerfile
    container_name: stakeholders-service
    restart: on-failure
    depends_on:
      - stakeholders-db
    networks:
      - app-network
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stakeholders-db:5432/stakeholdersdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SERVER_PORT: 8081
      FOLLOWER_SERVICE_URL: http://follower-service:5000
    volumes:
      - ./stakeholders-service/storage:/app/storage


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    networks:
      - app-network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - blog-db
      - stakeholders-db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  follower-db:
    image: neo4j:5
    container_name: follower-db
    restart: always
    networks:
      - app-network
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - follower-neo4j-data:/data

  tours-db:
    image: postgres:15
    container_name: tours-db
    restart: always
    networks:
      - app-network
    environment:
      POSTGRES_DB: toursdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - tours-db-data:/var/lib/postgresql/data

  tours-service:
    build:
      context: ./tour-service
      dockerfile: Dockerfile
    container_name: tours-service
    restart: on-failure
    depends_on:
      - tours-db
      - rabbitmq
    networks:
      - app-network
    ports:
      - "8083:8083"
      - "9093:9093"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://tours-db:5432/toursdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_SQL_INIT_MODE: always
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: true
      SERVER_PORT: 8083
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      JAVA_TOOL_OPTIONS: "-javaagent:/otel/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: tours-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
    volumes:
      - ./tour-service/uploads:/app/uploads
      - ./opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar

  follower-service:
    build:
      context: ./follower-service
      dockerfile: Dockerfile
    container_name: follower-service
    restart: on-failure
    depends_on:
      - follower-db
    networks:
      - app-network
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      ASPNETCORE_URLS: http://+:5000
      NEO4J_URI: bolt://follower-db:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: password

  purchase-db:
    image: postgres:15
    container_name: purchase-db
    restart: always
    networks:
      - app-network
    environment:
      POSTGRES_DB: purchase_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - purchase-db-data:/var/lib/postgresql/data

  purchase-service:
    build:
      context: ./purchase-service
      dockerfile: Dockerfile
    container_name: purchase-service
    restart: on-failure
    depends_on:
      - purchase-db
      - tours-service
      - rabbitmq
    networks:
      - app-network
    ports:
      - "8084:8084"
    environment:
      SERVER_PORT: 8084
      SPRING_DATASOURCE_URL: jdbc:postgresql://purchase-db:5432/purchase_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_SQL_INIT_MODE: always
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: true
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      APP_TEST_FAIL_TOKEN_CREATION: false
      JAVA_TOOL_OPTIONS: "-javaagent:/otel/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: purchase-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
    volumes:
      - ./opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    networks:
      - app-network
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: on-failure
    depends_on:
      - stakeholders-service
      - blog-service
      - tours-service
      - follower-service
      - purchase-service
    networks:
      - app-network
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      STAKEHOLDERS_SERVICE_URL: http://stakeholders-service:8081
      BLOG_SERVICE_URL: http://blog-service:8082
      TOURS_SERVICE_URL: http://tours-service:8083
      FOLLOWER_SERVICE_URL: http://follower-service:5000
      PURCHASE_SERVICE_URL: http://purchase-service:8084

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    restart: always
    networks:
      - app-network
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - prometheus

volumes:
  blog-db-data:
  stakeholders-db-data:
  pgadmin-data:
  tours-db-data:
  follower-neo4j-data:
  purchase-db-data:

networks:
  app-network:
    driver: bridge