spring.application.name=purchase-service

server.port=8084

spring.datasource.url=jdbc:postgresql://purchase-db:5432/purchase_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect