// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/blog.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlogRpcService_CreateComment_FullMethodName       = "/blog.BlogRpcService/CreateComment"
	BlogRpcService_GetCommentsByBlogId_FullMethodName = "/blog.BlogRpcService/GetCommentsByBlogId"
)

// BlogRpcServiceClient is the client API for BlogRpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlogRpcServiceClient interface {
	CreateComment(ctx context.Context, in *CreateCommentGrpcRequest, opts ...grpc.CallOption) (*CommentGrpcResponse, error)
	GetCommentsByBlogId(ctx context.Context, in *GetCommentsByBlogIdGrpcRequest, opts ...grpc.CallOption) (*GetCommentsGrpcResponse, error)
}

type blogRpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogRpcServiceClient(cc grpc.ClientConnInterface) BlogRpcServiceClient {
	return &blogRpcServiceClient{cc}
}

func (c *blogRpcServiceClient) CreateComment(ctx context.Context, in *CreateCommentGrpcRequest, opts ...grpc.CallOption) (*CommentGrpcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentGrpcResponse)
	err := c.cc.Invoke(ctx, BlogRpcService_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogRpcServiceClient) GetCommentsByBlogId(ctx context.Context, in *GetCommentsByBlogIdGrpcRequest, opts ...grpc.CallOption) (*GetCommentsGrpcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommentsGrpcResponse)
	err := c.cc.Invoke(ctx, BlogRpcService_GetCommentsByBlogId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogRpcServiceServer is the server API for BlogRpcService service.
// All implementations must embed UnimplementedBlogRpcServiceServer
// for forward compatibility.
type BlogRpcServiceServer interface {
	CreateComment(context.Context, *CreateCommentGrpcRequest) (*CommentGrpcResponse, error)
	GetCommentsByBlogId(context.Context, *GetCommentsByBlogIdGrpcRequest) (*GetCommentsGrpcResponse, error)
	mustEmbedUnimplementedBlogRpcServiceServer()
}

// UnimplementedBlogRpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlogRpcServiceServer struct{}

func (UnimplementedBlogRpcServiceServer) CreateComment(context.Context, *CreateCommentGrpcRequest) (*CommentGrpcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedBlogRpcServiceServer) GetCommentsByBlogId(context.Context, *GetCommentsByBlogIdGrpcRequest) (*GetCommentsGrpcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommentsByBlogId not implemented")
}
func (UnimplementedBlogRpcServiceServer) mustEmbedUnimplementedBlogRpcServiceServer() {}
func (UnimplementedBlogRpcServiceServer) testEmbeddedByValue()                        {}

// UnsafeBlogRpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlogRpcServiceServer will
// result in compilation errors.
type UnsafeBlogRpcServiceServer interface {
	mustEmbedUnimplementedBlogRpcServiceServer()
}

func RegisterBlogRpcServiceServer(s grpc.ServiceRegistrar, srv BlogRpcServiceServer) {
	// If the following call panics, it indicates UnimplementedBlogRpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlogRpcService_ServiceDesc, srv)
}

func _BlogRpcService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentGrpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogRpcServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogRpcService_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogRpcServiceServer).CreateComment(ctx, req.(*CreateCommentGrpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogRpcService_GetCommentsByBlogId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentsByBlogIdGrpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogRpcServiceServer).GetCommentsByBlogId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogRpcService_GetCommentsByBlogId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogRpcServiceServer).GetCommentsByBlogId(ctx, req.(*GetCommentsByBlogIdGrpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlogRpcService_ServiceDesc is the grpc.ServiceDesc for BlogRpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlogRpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blog.BlogRpcService",
	HandlerType: (*BlogRpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateComment",
			Handler:    _BlogRpcService_CreateComment_Handler,
		},
		{
			MethodName: "GetCommentsByBlogId",
			Handler:    _BlogRpcService_GetCommentsByBlogId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/blog.proto",
}
