// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/stakeholders.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterGrpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterGrpcRequest) Reset() {
	*x = RegisterGrpcRequest{}
	mi := &file_proto_stakeholders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterGrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterGrpcRequest) ProtoMessage() {}

func (x *RegisterGrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stakeholders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterGrpcRequest.ProtoReflect.Descriptor instead.
func (*RegisterGrpcRequest) Descriptor() ([]byte, []int) {
	return file_proto_stakeholders_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterGrpcRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterGrpcRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterGrpcRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterGrpcRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type LoginGrpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginGrpcRequest) Reset() {
	*x = LoginGrpcRequest{}
	mi := &file_proto_stakeholders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginGrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginGrpcRequest) ProtoMessage() {}

func (x *LoginGrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stakeholders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginGrpcRequest.ProtoReflect.Descriptor instead.
func (*LoginGrpcRequest) Descriptor() ([]byte, []int) {
	return file_proto_stakeholders_proto_rawDescGZIP(), []int{1}
}

func (x *LoginGrpcRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginGrpcRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserGrpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Blocked       bool                   `protobuf:"varint,5,opt,name=blocked,proto3" json:"blocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGrpcResponse) Reset() {
	*x = UserGrpcResponse{}
	mi := &file_proto_stakeholders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGrpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGrpcResponse) ProtoMessage() {}

func (x *UserGrpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stakeholders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGrpcResponse.ProtoReflect.Descriptor instead.
func (*UserGrpcResponse) Descriptor() ([]byte, []int) {
	return file_proto_stakeholders_proto_rawDescGZIP(), []int{2}
}

func (x *UserGrpcResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserGrpcResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserGrpcResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserGrpcResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserGrpcResponse) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

type AuthGrpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User          *UserGrpcResponse      `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthGrpcResponse) Reset() {
	*x = AuthGrpcResponse{}
	mi := &file_proto_stakeholders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthGrpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthGrpcResponse) ProtoMessage() {}

func (x *AuthGrpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stakeholders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthGrpcResponse.ProtoReflect.Descriptor instead.
func (*AuthGrpcResponse) Descriptor() ([]byte, []int) {
	return file_proto_stakeholders_proto_rawDescGZIP(), []int{3}
}

func (x *AuthGrpcResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthGrpcResponse) GetUser() *UserGrpcResponse {
	if x != nil {
		return x.User
	}
	return nil
}

var File_proto_stakeholders_proto protoreflect.FileDescriptor

const file_proto_stakeholders_proto_rawDesc = "" +
	"\n" +
	"\x18proto/stakeholders.proto\"w\n" +
	"\x13RegisterGrpcRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"J\n" +
	"\x10LoginGrpcRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x82\x01\n" +
	"\x10UserGrpcResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x18\n" +
	"\ablocked\x18\x05 \x01(\bR\ablocked\"O\n" +
	"\x10AuthGrpcResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12%\n" +
	"\x04user\x18\x02 \x01(\v2\x11.UserGrpcResponseR\x04user2t\n" +
	"\x0eAuthRpcService\x123\n" +
	"\bRegister\x12\x14.RegisterGrpcRequest\x1a\x11.UserGrpcResponse\x12-\n" +
	"\x05Login\x12\x11.LoginGrpcRequest\x1a\x11.AuthGrpcResponseBK\n" +
	"!com.soa.stakeholders_service.grpcB\x11StakeholdersProtoP\x01Z\x11api-gateway/protob\x06proto3"

var (
	file_proto_stakeholders_proto_rawDescOnce sync.Once
	file_proto_stakeholders_proto_rawDescData []byte
)

func file_proto_stakeholders_proto_rawDescGZIP() []byte {
	file_proto_stakeholders_proto_rawDescOnce.Do(func() {
		file_proto_stakeholders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stakeholders_proto_rawDesc), len(file_proto_stakeholders_proto_rawDesc)))
	})
	return file_proto_stakeholders_proto_rawDescData
}

var file_proto_stakeholders_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_stakeholders_proto_goTypes = []any{
	(*RegisterGrpcRequest)(nil), // 0: RegisterGrpcRequest
	(*LoginGrpcRequest)(nil),    // 1: LoginGrpcRequest
	(*UserGrpcResponse)(nil),    // 2: UserGrpcResponse
	(*AuthGrpcResponse)(nil),    // 3: AuthGrpcResponse
}
var file_proto_stakeholders_proto_depIdxs = []int32{
	2, // 0: AuthGrpcResponse.user:type_name -> UserGrpcResponse
	0, // 1: AuthRpcService.Register:input_type -> RegisterGrpcRequest
	1, // 2: AuthRpcService.Login:input_type -> LoginGrpcRequest
	2, // 3: AuthRpcService.Register:output_type -> UserGrpcResponse
	3, // 4: AuthRpcService.Login:output_type -> AuthGrpcResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_stakeholders_proto_init() }
func file_proto_stakeholders_proto_init() {
	if File_proto_stakeholders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stakeholders_proto_rawDesc), len(file_proto_stakeholders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stakeholders_proto_goTypes,
		DependencyIndexes: file_proto_stakeholders_proto_depIdxs,
		MessageInfos:      file_proto_stakeholders_proto_msgTypes,
	}.Build()
	File_proto_stakeholders_proto = out.File
	file_proto_stakeholders_proto_goTypes = nil
	file_proto_stakeholders_proto_depIdxs = nil
}
