// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/stakeholders.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthRpcService_Register_FullMethodName = "/AuthRpcService/Register"
	AuthRpcService_Login_FullMethodName    = "/AuthRpcService/Login"
)

// AuthRpcServiceClient is the client API for AuthRpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthRpcServiceClient interface {
	Register(ctx context.Context, in *RegisterGrpcRequest, opts ...grpc.CallOption) (*UserGrpcResponse, error)
	Login(ctx context.Context, in *LoginGrpcRequest, opts ...grpc.CallOption) (*AuthGrpcResponse, error)
}

type authRpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthRpcServiceClient(cc grpc.ClientConnInterface) AuthRpcServiceClient {
	return &authRpcServiceClient{cc}
}

func (c *authRpcServiceClient) Register(ctx context.Context, in *RegisterGrpcRequest, opts ...grpc.CallOption) (*UserGrpcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserGrpcResponse)
	err := c.cc.Invoke(ctx, AuthRpcService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authRpcServiceClient) Login(ctx context.Context, in *LoginGrpcRequest, opts ...grpc.CallOption) (*AuthGrpcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthGrpcResponse)
	err := c.cc.Invoke(ctx, AuthRpcService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthRpcServiceServer is the server API for AuthRpcService service.
// All implementations must embed UnimplementedAuthRpcServiceServer
// for forward compatibility.
type AuthRpcServiceServer interface {
	Register(context.Context, *RegisterGrpcRequest) (*UserGrpcResponse, error)
	Login(context.Context, *LoginGrpcRequest) (*AuthGrpcResponse, error)
	mustEmbedUnimplementedAuthRpcServiceServer()
}

// UnimplementedAuthRpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthRpcServiceServer struct{}

func (UnimplementedAuthRpcServiceServer) Register(context.Context, *RegisterGrpcRequest) (*UserGrpcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAuthRpcServiceServer) Login(context.Context, *LoginGrpcRequest) (*AuthGrpcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthRpcServiceServer) mustEmbedUnimplementedAuthRpcServiceServer() {}
func (UnimplementedAuthRpcServiceServer) testEmbeddedByValue()                        {}

// UnsafeAuthRpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthRpcServiceServer will
// result in compilation errors.
type UnsafeAuthRpcServiceServer interface {
	mustEmbedUnimplementedAuthRpcServiceServer()
}

func RegisterAuthRpcServiceServer(s grpc.ServiceRegistrar, srv AuthRpcServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthRpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthRpcService_ServiceDesc, srv)
}

func _AuthRpcService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterGrpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthRpcServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthRpcService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthRpcServiceServer).Register(ctx, req.(*RegisterGrpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthRpcService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginGrpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthRpcServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthRpcService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthRpcServiceServer).Login(ctx, req.(*LoginGrpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthRpcService_ServiceDesc is the grpc.ServiceDesc for AuthRpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthRpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AuthRpcService",
	HandlerType: (*AuthRpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AuthRpcService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthRpcService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/stakeholders.proto",
}
