// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/tour.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TourRpcService_GetPublishedTours_FullMethodName = "/TourRpcService/GetPublishedTours"
	TourRpcService_GetTourById_FullMethodName       = "/TourRpcService/GetTourById"
	TourRpcService_GetMyTours_FullMethodName        = "/TourRpcService/GetMyTours"
)

// TourRpcServiceClient is the client API for TourRpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TourRpcServiceClient interface {
	GetPublishedTours(ctx context.Context, in *GetPublishedToursRequest, opts ...grpc.CallOption) (*TourListGrpcResponse, error)
	GetTourById(ctx context.Context, in *GetTourByIdRequest, opts ...grpc.CallOption) (*TourGrpcResponse, error)
	GetMyTours(ctx context.Context, in *GetMyToursRequest, opts ...grpc.CallOption) (*TourListGrpcResponse, error)
}

type tourRpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTourRpcServiceClient(cc grpc.ClientConnInterface) TourRpcServiceClient {
	return &tourRpcServiceClient{cc}
}

func (c *tourRpcServiceClient) GetPublishedTours(ctx context.Context, in *GetPublishedToursRequest, opts ...grpc.CallOption) (*TourListGrpcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourListGrpcResponse)
	err := c.cc.Invoke(ctx, TourRpcService_GetPublishedTours_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourRpcServiceClient) GetTourById(ctx context.Context, in *GetTourByIdRequest, opts ...grpc.CallOption) (*TourGrpcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourGrpcResponse)
	err := c.cc.Invoke(ctx, TourRpcService_GetTourById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourRpcServiceClient) GetMyTours(ctx context.Context, in *GetMyToursRequest, opts ...grpc.CallOption) (*TourListGrpcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourListGrpcResponse)
	err := c.cc.Invoke(ctx, TourRpcService_GetMyTours_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourRpcServiceServer is the server API for TourRpcService service.
// All implementations must embed UnimplementedTourRpcServiceServer
// for forward compatibility.
type TourRpcServiceServer interface {
	GetPublishedTours(context.Context, *GetPublishedToursRequest) (*TourListGrpcResponse, error)
	GetTourById(context.Context, *GetTourByIdRequest) (*TourGrpcResponse, error)
	GetMyTours(context.Context, *GetMyToursRequest) (*TourListGrpcResponse, error)
	mustEmbedUnimplementedTourRpcServiceServer()
}

// UnimplementedTourRpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTourRpcServiceServer struct{}

func (UnimplementedTourRpcServiceServer) GetPublishedTours(context.Context, *GetPublishedToursRequest) (*TourListGrpcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublishedTours not implemented")
}
func (UnimplementedTourRpcServiceServer) GetTourById(context.Context, *GetTourByIdRequest) (*TourGrpcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTourById not implemented")
}
func (UnimplementedTourRpcServiceServer) GetMyTours(context.Context, *GetMyToursRequest) (*TourListGrpcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyTours not implemented")
}
func (UnimplementedTourRpcServiceServer) mustEmbedUnimplementedTourRpcServiceServer() {}
func (UnimplementedTourRpcServiceServer) testEmbeddedByValue()                        {}

// UnsafeTourRpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourRpcServiceServer will
// result in compilation errors.
type UnsafeTourRpcServiceServer interface {
	mustEmbedUnimplementedTourRpcServiceServer()
}

func RegisterTourRpcServiceServer(s grpc.ServiceRegistrar, srv TourRpcServiceServer) {
	// If the following call panics, it indicates UnimplementedTourRpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TourRpcService_ServiceDesc, srv)
}

func _TourRpcService_GetPublishedTours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublishedToursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourRpcServiceServer).GetPublishedTours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourRpcService_GetPublishedTours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourRpcServiceServer).GetPublishedTours(ctx, req.(*GetPublishedToursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourRpcService_GetTourById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTourByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourRpcServiceServer).GetTourById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourRpcService_GetTourById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourRpcServiceServer).GetTourById(ctx, req.(*GetTourByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourRpcService_GetMyTours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyToursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourRpcServiceServer).GetMyTours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourRpcService_GetMyTours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourRpcServiceServer).GetMyTours(ctx, req.(*GetMyToursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TourRpcService_ServiceDesc is the grpc.ServiceDesc for TourRpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TourRpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TourRpcService",
	HandlerType: (*TourRpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublishedTours",
			Handler:    _TourRpcService_GetPublishedTours_Handler,
		},
		{
			MethodName: "GetTourById",
			Handler:    _TourRpcService_GetTourById_Handler,
		},
		{
			MethodName: "GetMyTours",
			Handler:    _TourRpcService_GetMyTours_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tour.proto",
}
