// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/tour.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPublishedToursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     int64                  `protobuf:"varint,1,opt,name=touristId,proto3" json:"touristId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishedToursRequest) Reset() {
	*x = GetPublishedToursRequest{}
	mi := &file_proto_tour_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishedToursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishedToursRequest) ProtoMessage() {}

func (x *GetPublishedToursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishedToursRequest.ProtoReflect.Descriptor instead.
func (*GetPublishedToursRequest) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{0}
}

func (x *GetPublishedToursRequest) GetTouristId() int64 {
	if x != nil {
		return x.TouristId
	}
	return 0
}

type GetTourByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        int64                  `protobuf:"varint,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourByIdRequest) Reset() {
	*x = GetTourByIdRequest{}
	mi := &file_proto_tour_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourByIdRequest) ProtoMessage() {}

func (x *GetTourByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTourByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{1}
}

func (x *GetTourByIdRequest) GetTourId() int64 {
	if x != nil {
		return x.TourId
	}
	return 0
}

func (x *GetTourByIdRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetTourByIdRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GetMyToursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=authorId,proto3" json:"authorId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyToursRequest) Reset() {
	*x = GetMyToursRequest{}
	mi := &file_proto_tour_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyToursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyToursRequest) ProtoMessage() {}

func (x *GetMyToursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyToursRequest.ProtoReflect.Descriptor instead.
func (*GetMyToursRequest) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{2}
}

func (x *GetMyToursRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type TourListGrpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*TourGrpcResponse    `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourListGrpcResponse) Reset() {
	*x = TourListGrpcResponse{}
	mi := &file_proto_tour_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourListGrpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourListGrpcResponse) ProtoMessage() {}

func (x *TourListGrpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourListGrpcResponse.ProtoReflect.Descriptor instead.
func (*TourListGrpcResponse) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{3}
}

func (x *TourListGrpcResponse) GetTours() []*TourGrpcResponse {
	if x != nil {
		return x.Tours
	}
	return nil
}

type TourTransportTimeGrpcResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TransportType   string                 `protobuf:"bytes,2,opt,name=transportType,proto3" json:"transportType,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,3,opt,name=durationMinutes,proto3" json:"durationMinutes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TourTransportTimeGrpcResponse) Reset() {
	*x = TourTransportTimeGrpcResponse{}
	mi := &file_proto_tour_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourTransportTimeGrpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourTransportTimeGrpcResponse) ProtoMessage() {}

func (x *TourTransportTimeGrpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourTransportTimeGrpcResponse.ProtoReflect.Descriptor instead.
func (*TourTransportTimeGrpcResponse) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{4}
}

func (x *TourTransportTimeGrpcResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TourTransportTimeGrpcResponse) GetTransportType() string {
	if x != nil {
		return x.TransportType
	}
	return ""
}

func (x *TourTransportTimeGrpcResponse) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

type TourGrpcResponse struct {
	state          protoimpl.MessageState           `protogen:"open.v1"`
	Id             int64                            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                           `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty     string                           `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Price          float64                          `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Status         string                           `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	AuthorId       int64                            `protobuf:"varint,7,opt,name=authorId,proto3" json:"authorId,omitempty"`
	DistanceInKm   float64                          `protobuf:"fixed64,8,opt,name=distanceInKm,proto3" json:"distanceInKm,omitempty"`
	TransportTimes []*TourTransportTimeGrpcResponse `protobuf:"bytes,9,rep,name=transportTimes,proto3" json:"transportTimes,omitempty"`
	InShoppingCart bool                             `protobuf:"varint,10,opt,name=inShoppingCart,proto3" json:"inShoppingCart,omitempty"`
	Purchased      bool                             `protobuf:"varint,11,opt,name=purchased,proto3" json:"purchased,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TourGrpcResponse) Reset() {
	*x = TourGrpcResponse{}
	mi := &file_proto_tour_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourGrpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourGrpcResponse) ProtoMessage() {}

func (x *TourGrpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourGrpcResponse.ProtoReflect.Descriptor instead.
func (*TourGrpcResponse) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{5}
}

func (x *TourGrpcResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TourGrpcResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TourGrpcResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TourGrpcResponse) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *TourGrpcResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TourGrpcResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TourGrpcResponse) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *TourGrpcResponse) GetDistanceInKm() float64 {
	if x != nil {
		return x.DistanceInKm
	}
	return 0
}

func (x *TourGrpcResponse) GetTransportTimes() []*TourTransportTimeGrpcResponse {
	if x != nil {
		return x.TransportTimes
	}
	return nil
}

func (x *TourGrpcResponse) GetInShoppingCart() bool {
	if x != nil {
		return x.InShoppingCart
	}
	return false
}

func (x *TourGrpcResponse) GetPurchased() bool {
	if x != nil {
		return x.Purchased
	}
	return false
}

var File_proto_tour_proto protoreflect.FileDescriptor

const file_proto_tour_proto_rawDesc = "" +
	"\n" +
	"\x10proto/tour.proto\"8\n" +
	"\x18GetPublishedToursRequest\x12\x1c\n" +
	"\ttouristId\x18\x01 \x01(\x03R\ttouristId\"X\n" +
	"\x12GetTourByIdRequest\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\x03R\x06tourId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"/\n" +
	"\x11GetMyToursRequest\x12\x1a\n" +
	"\bauthorId\x18\x01 \x01(\x03R\bauthorId\"?\n" +
	"\x14TourListGrpcResponse\x12'\n" +
	"\x05tours\x18\x01 \x03(\v2\x11.TourGrpcResponseR\x05tours\"\x7f\n" +
	"\x1dTourTransportTimeGrpcResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12$\n" +
	"\rtransportType\x18\x02 \x01(\tR\rtransportType\x12(\n" +
	"\x0fdurationMinutes\x18\x03 \x01(\x05R\x0fdurationMinutes\"\xf4\x02\n" +
	"\x10TourGrpcResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1a\n" +
	"\bauthorId\x18\a \x01(\x03R\bauthorId\x12\"\n" +
	"\fdistanceInKm\x18\b \x01(\x01R\fdistanceInKm\x12F\n" +
	"\x0etransportTimes\x18\t \x03(\v2\x1e.TourTransportTimeGrpcResponseR\x0etransportTimes\x12&\n" +
	"\x0einShoppingCart\x18\n" +
	" \x01(\bR\x0einShoppingCart\x12\x1c\n" +
	"\tpurchased\x18\v \x01(\bR\tpurchased2\xc7\x01\n" +
	"\x0eTourRpcService\x12E\n" +
	"\x11GetPublishedTours\x12\x19.GetPublishedToursRequest\x1a\x15.TourListGrpcResponse\x125\n" +
	"\vGetTourById\x12\x13.GetTourByIdRequest\x1a\x11.TourGrpcResponse\x127\n" +
	"\n" +
	"GetMyTours\x12\x12.GetMyToursRequest\x1a\x15.TourListGrpcResponseB1\n" +
	"\x19com.soa.tour_service.grpcB\tTourProtoP\x01Z\a./protob\x06proto3"

var (
	file_proto_tour_proto_rawDescOnce sync.Once
	file_proto_tour_proto_rawDescData []byte
)

func file_proto_tour_proto_rawDescGZIP() []byte {
	file_proto_tour_proto_rawDescOnce.Do(func() {
		file_proto_tour_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tour_proto_rawDesc), len(file_proto_tour_proto_rawDesc)))
	})
	return file_proto_tour_proto_rawDescData
}

var file_proto_tour_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_tour_proto_goTypes = []any{
	(*GetPublishedToursRequest)(nil),      // 0: GetPublishedToursRequest
	(*GetTourByIdRequest)(nil),            // 1: GetTourByIdRequest
	(*GetMyToursRequest)(nil),             // 2: GetMyToursRequest
	(*TourListGrpcResponse)(nil),          // 3: TourListGrpcResponse
	(*TourTransportTimeGrpcResponse)(nil), // 4: TourTransportTimeGrpcResponse
	(*TourGrpcResponse)(nil),              // 5: TourGrpcResponse
}
var file_proto_tour_proto_depIdxs = []int32{
	5, // 0: TourListGrpcResponse.tours:type_name -> TourGrpcResponse
	4, // 1: TourGrpcResponse.transportTimes:type_name -> TourTransportTimeGrpcResponse
	0, // 2: TourRpcService.GetPublishedTours:input_type -> GetPublishedToursRequest
	1, // 3: TourRpcService.GetTourById:input_type -> GetTourByIdRequest
	2, // 4: TourRpcService.GetMyTours:input_type -> GetMyToursRequest
	3, // 5: TourRpcService.GetPublishedTours:output_type -> TourListGrpcResponse
	5, // 6: TourRpcService.GetTourById:output_type -> TourGrpcResponse
	3, // 7: TourRpcService.GetMyTours:output_type -> TourListGrpcResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_tour_proto_init() }
func file_proto_tour_proto_init() {
	if File_proto_tour_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tour_proto_rawDesc), len(file_proto_tour_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tour_proto_goTypes,
		DependencyIndexes: file_proto_tour_proto_depIdxs,
		MessageInfos:      file_proto_tour_proto_msgTypes,
	}.Build()
	File_proto_tour_proto = out.File
	file_proto_tour_proto_goTypes = nil
	file_proto_tour_proto_depIdxs = nil
}
