spring.application.name=blog-service
server.port=${SERVER_PORT:8082}

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/blog_db}

jwt.secret=1234567890123456789012345678901212345678901234567890123456789012
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

app.upload-dir=${UPLOAD_DIR:blog-service/uploads}
follower.service.url=${FOLLOWER_SERVICE_URL:http://localhost:5000}

grpc.client.follower-service.address=static://localhost:5000
grpc.client.follower-service.negotiation-type=plaintext
grpc.server.port=9092