// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tour.proto

package com.soa.tour_service.grpc;

public interface GetMyToursRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetMyToursRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 authorId = 1;</code>
   * @return The authorId.
   */
  long getAuthorId();
}
