// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tour.proto

package com.soa.tour_service.grpc;

public interface GetPublishedToursRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetPublishedToursRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 touristId = 1;</code>
   * @return The touristId.
   */
  long getTouristId();
}
