// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tour.proto

package com.soa.tour_service.grpc;

/**
 * Protobuf type {@code GetPublishedToursRequest}
 */
public  final class GetPublishedToursRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetPublishedToursRequest)
    GetPublishedToursRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetPublishedToursRequest.newBuilder() to construct.
  private GetPublishedToursRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetPublishedToursRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetPublishedToursRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetPublishedToursRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            touristId_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.soa.tour_service.grpc.TourProto.internal_static_GetPublishedToursRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.soa.tour_service.grpc.TourProto.internal_static_GetPublishedToursRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.soa.tour_service.grpc.GetPublishedToursRequest.class, com.soa.tour_service.grpc.GetPublishedToursRequest.Builder.class);
  }

  public static final int TOURISTID_FIELD_NUMBER = 1;
  private long touristId_;
  /**
   * <code>int64 touristId = 1;</code>
   * @return The touristId.
   */
  public long getTouristId() {
    return touristId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (touristId_ != 0L) {
      output.writeInt64(1, touristId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (touristId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, touristId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.soa.tour_service.grpc.GetPublishedToursRequest)) {
      return super.equals(obj);
    }
    com.soa.tour_service.grpc.GetPublishedToursRequest other = (com.soa.tour_service.grpc.GetPublishedToursRequest) obj;

    if (getTouristId()
        != other.getTouristId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOURISTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTouristId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.soa.tour_service.grpc.GetPublishedToursRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.soa.tour_service.grpc.GetPublishedToursRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.soa.tour_service.grpc.GetPublishedToursRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.soa.tour_service.grpc.GetPublishedToursRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.soa.tour_service.grpc.GetPublishedToursRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.soa.tour_service.grpc.GetPublishedToursRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.soa.tour_service.grpc.GetPublishedToursRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.soa.tour_service.grpc.GetPublishedToursRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.soa.tour_service.grpc.GetPublishedToursRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.soa.tour_service.grpc.GetPublishedToursRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.soa.tour_service.grpc.GetPublishedToursRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.soa.tour_service.grpc.GetPublishedToursRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.soa.tour_service.grpc.GetPublishedToursRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetPublishedToursRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetPublishedToursRequest)
      com.soa.tour_service.grpc.GetPublishedToursRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.soa.tour_service.grpc.TourProto.internal_static_GetPublishedToursRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.soa.tour_service.grpc.TourProto.internal_static_GetPublishedToursRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.soa.tour_service.grpc.GetPublishedToursRequest.class, com.soa.tour_service.grpc.GetPublishedToursRequest.Builder.class);
    }

    // Construct using com.soa.tour_service.grpc.GetPublishedToursRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      touristId_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.soa.tour_service.grpc.TourProto.internal_static_GetPublishedToursRequest_descriptor;
    }

    @java.lang.Override
    public com.soa.tour_service.grpc.GetPublishedToursRequest getDefaultInstanceForType() {
      return com.soa.tour_service.grpc.GetPublishedToursRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.soa.tour_service.grpc.GetPublishedToursRequest build() {
      com.soa.tour_service.grpc.GetPublishedToursRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.soa.tour_service.grpc.GetPublishedToursRequest buildPartial() {
      com.soa.tour_service.grpc.GetPublishedToursRequest result = new com.soa.tour_service.grpc.GetPublishedToursRequest(this);
      result.touristId_ = touristId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.soa.tour_service.grpc.GetPublishedToursRequest) {
        return mergeFrom((com.soa.tour_service.grpc.GetPublishedToursRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.soa.tour_service.grpc.GetPublishedToursRequest other) {
      if (other == com.soa.tour_service.grpc.GetPublishedToursRequest.getDefaultInstance()) return this;
      if (other.getTouristId() != 0L) {
        setTouristId(other.getTouristId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.soa.tour_service.grpc.GetPublishedToursRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.soa.tour_service.grpc.GetPublishedToursRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long touristId_ ;
    /**
     * <code>int64 touristId = 1;</code>
     * @return The touristId.
     */
    public long getTouristId() {
      return touristId_;
    }
    /**
     * <code>int64 touristId = 1;</code>
     * @param value The touristId to set.
     * @return This builder for chaining.
     */
    public Builder setTouristId(long value) {
      
      touristId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 touristId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTouristId() {
      
      touristId_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetPublishedToursRequest)
  }

  // @@protoc_insertion_point(class_scope:GetPublishedToursRequest)
  private static final com.soa.tour_service.grpc.GetPublishedToursRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.soa.tour_service.grpc.GetPublishedToursRequest();
  }

  public static com.soa.tour_service.grpc.GetPublishedToursRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetPublishedToursRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetPublishedToursRequest>() {
    @java.lang.Override
    public GetPublishedToursRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetPublishedToursRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetPublishedToursRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetPublishedToursRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.soa.tour_service.grpc.GetPublishedToursRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

