// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tour.proto

package com.soa.tour_service.grpc;

public interface GetTourByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetTourByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 tourId = 1;</code>
   * @return The tourId.
   */
  long getTourId();

  /**
   * <code>int64 userId = 2;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>string role = 3;</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <code>string role = 3;</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();
}
