// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tour.proto

package com.soa.tour_service.grpc;

public interface TourListGrpcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TourListGrpcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .TourGrpcResponse tours = 1;</code>
   */
  java.util.List<com.soa.tour_service.grpc.TourGrpcResponse> 
      getToursList();
  /**
   * <code>repeated .TourGrpcResponse tours = 1;</code>
   */
  com.soa.tour_service.grpc.TourGrpcResponse getTours(int index);
  /**
   * <code>repeated .TourGrpcResponse tours = 1;</code>
   */
  int getToursCount();
  /**
   * <code>repeated .TourGrpcResponse tours = 1;</code>
   */
  java.util.List<? extends com.soa.tour_service.grpc.TourGrpcResponseOrBuilder> 
      getToursOrBuilderList();
  /**
   * <code>repeated .TourGrpcResponse tours = 1;</code>
   */
  com.soa.tour_service.grpc.TourGrpcResponseOrBuilder getToursOrBuilder(
      int index);
}
