// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tour.proto

package com.soa.tour_service.grpc;

public final class TourProto {
  private TourProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPublishedToursRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPublishedToursRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetTourByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetTourByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetMyToursRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetMyToursRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TourListGrpcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TourListGrpcResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TourTransportTimeGrpcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TourTransportTimeGrpcResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TourGrpcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TourGrpcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntour.proto\"-\n\030GetPublishedToursRequest" +
      "\022\021\n\ttouristId\030\001 \001(\003\"B\n\022GetTourByIdReques" +
      "t\022\016\n\006tourId\030\001 \001(\003\022\016\n\006userId\030\002 \001(\003\022\014\n\004rol" +
      "e\030\003 \001(\t\"%\n\021GetMyToursRequest\022\020\n\010authorId" +
      "\030\001 \001(\003\"8\n\024TourListGrpcResponse\022 \n\005tours\030" +
      "\001 \003(\0132\021.TourGrpcResponse\"[\n\035TourTranspor" +
      "tTimeGrpcResponse\022\n\n\002id\030\001 \001(\003\022\025\n\rtranspo" +
      "rtType\030\002 \001(\t\022\027\n\017durationMinutes\030\003 \001(\005\"\377\001" +
      "\n\020TourGrpcResponse\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002" +
      " \001(\t\022\023\n\013description\030\003 \001(\t\022\022\n\ndifficulty\030" +
      "\004 \001(\t\022\r\n\005price\030\005 \001(\001\022\016\n\006status\030\006 \001(\t\022\020\n\010" +
      "authorId\030\007 \001(\003\022\024\n\014distanceInKm\030\010 \001(\001\0226\n\016" +
      "transportTimes\030\t \003(\0132\036.TourTransportTime" +
      "GrpcResponse\022\026\n\016inShoppingCart\030\n \001(\010\022\021\n\t" +
      "purchased\030\013 \001(\0102\307\001\n\016TourRpcService\022E\n\021Ge" +
      "tPublishedTours\022\031.GetPublishedToursReque" +
      "st\032\025.TourListGrpcResponse\0225\n\013GetTourById" +
      "\022\023.GetTourByIdRequest\032\021.TourGrpcResponse" +
      "\0227\n\nGetMyTours\022\022.GetMyToursRequest\032\025.Tou" +
      "rListGrpcResponseB(\n\031com.soa.tour_servic" +
      "e.grpcB\tTourProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetPublishedToursRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetPublishedToursRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPublishedToursRequest_descriptor,
        new java.lang.String[] { "TouristId", });
    internal_static_GetTourByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetTourByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetTourByIdRequest_descriptor,
        new java.lang.String[] { "TourId", "UserId", "Role", });
    internal_static_GetMyToursRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetMyToursRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetMyToursRequest_descriptor,
        new java.lang.String[] { "AuthorId", });
    internal_static_TourListGrpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_TourListGrpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TourListGrpcResponse_descriptor,
        new java.lang.String[] { "Tours", });
    internal_static_TourTransportTimeGrpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_TourTransportTimeGrpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TourTransportTimeGrpcResponse_descriptor,
        new java.lang.String[] { "Id", "TransportType", "DurationMinutes", });
    internal_static_TourGrpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_TourGrpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TourGrpcResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Difficulty", "Price", "Status", "AuthorId", "DistanceInKm", "TransportTimes", "InShoppingCart", "Purchased", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
