// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tour.proto

package com.soa.tour_service.grpc;

public interface TourGrpcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TourGrpcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string difficulty = 4;</code>
   * @return The difficulty.
   */
  java.lang.String getDifficulty();
  /**
   * <code>string difficulty = 4;</code>
   * @return The bytes for difficulty.
   */
  com.google.protobuf.ByteString
      getDifficultyBytes();

  /**
   * <code>double price = 5;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>string status = 6;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 6;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int64 authorId = 7;</code>
   * @return The authorId.
   */
  long getAuthorId();

  /**
   * <code>double distanceInKm = 8;</code>
   * @return The distanceInKm.
   */
  double getDistanceInKm();

  /**
   * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
   */
  java.util.List<com.soa.tour_service.grpc.TourTransportTimeGrpcResponse> 
      getTransportTimesList();
  /**
   * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
   */
  com.soa.tour_service.grpc.TourTransportTimeGrpcResponse getTransportTimes(int index);
  /**
   * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
   */
  int getTransportTimesCount();
  /**
   * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
   */
  java.util.List<? extends com.soa.tour_service.grpc.TourTransportTimeGrpcResponseOrBuilder> 
      getTransportTimesOrBuilderList();
  /**
   * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
   */
  com.soa.tour_service.grpc.TourTransportTimeGrpcResponseOrBuilder getTransportTimesOrBuilder(
      int index);

  /**
   * <code>bool inShoppingCart = 10;</code>
   * @return The inShoppingCart.
   */
  boolean getInShoppingCart();

  /**
   * <code>bool purchased = 11;</code>
   * @return The purchased.
   */
  boolean getPurchased();
}
