// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tour.proto

package com.soa.tour_service.grpc;

/**
 * Protobuf type {@code TourListGrpcResponse}
 */
public  final class TourListGrpcResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TourListGrpcResponse)
    TourListGrpcResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TourListGrpcResponse.newBuilder() to construct.
  private TourListGrpcResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TourListGrpcResponse() {
    tours_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TourListGrpcResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TourListGrpcResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              tours_ = new java.util.ArrayList<com.soa.tour_service.grpc.TourGrpcResponse>();
              mutable_bitField0_ |= 0x00000001;
            }
            tours_.add(
                input.readMessage(com.soa.tour_service.grpc.TourGrpcResponse.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        tours_ = java.util.Collections.unmodifiableList(tours_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.soa.tour_service.grpc.TourProto.internal_static_TourListGrpcResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.soa.tour_service.grpc.TourProto.internal_static_TourListGrpcResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.soa.tour_service.grpc.TourListGrpcResponse.class, com.soa.tour_service.grpc.TourListGrpcResponse.Builder.class);
  }

  public static final int TOURS_FIELD_NUMBER = 1;
  private java.util.List<com.soa.tour_service.grpc.TourGrpcResponse> tours_;
  /**
   * <code>repeated .TourGrpcResponse tours = 1;</code>
   */
  public java.util.List<com.soa.tour_service.grpc.TourGrpcResponse> getToursList() {
    return tours_;
  }
  /**
   * <code>repeated .TourGrpcResponse tours = 1;</code>
   */
  public java.util.List<? extends com.soa.tour_service.grpc.TourGrpcResponseOrBuilder> 
      getToursOrBuilderList() {
    return tours_;
  }
  /**
   * <code>repeated .TourGrpcResponse tours = 1;</code>
   */
  public int getToursCount() {
    return tours_.size();
  }
  /**
   * <code>repeated .TourGrpcResponse tours = 1;</code>
   */
  public com.soa.tour_service.grpc.TourGrpcResponse getTours(int index) {
    return tours_.get(index);
  }
  /**
   * <code>repeated .TourGrpcResponse tours = 1;</code>
   */
  public com.soa.tour_service.grpc.TourGrpcResponseOrBuilder getToursOrBuilder(
      int index) {
    return tours_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < tours_.size(); i++) {
      output.writeMessage(1, tours_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < tours_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, tours_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.soa.tour_service.grpc.TourListGrpcResponse)) {
      return super.equals(obj);
    }
    com.soa.tour_service.grpc.TourListGrpcResponse other = (com.soa.tour_service.grpc.TourListGrpcResponse) obj;

    if (!getToursList()
        .equals(other.getToursList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getToursCount() > 0) {
      hash = (37 * hash) + TOURS_FIELD_NUMBER;
      hash = (53 * hash) + getToursList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.soa.tour_service.grpc.TourListGrpcResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.soa.tour_service.grpc.TourListGrpcResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.soa.tour_service.grpc.TourListGrpcResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.soa.tour_service.grpc.TourListGrpcResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.soa.tour_service.grpc.TourListGrpcResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.soa.tour_service.grpc.TourListGrpcResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.soa.tour_service.grpc.TourListGrpcResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.soa.tour_service.grpc.TourListGrpcResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.soa.tour_service.grpc.TourListGrpcResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.soa.tour_service.grpc.TourListGrpcResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.soa.tour_service.grpc.TourListGrpcResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.soa.tour_service.grpc.TourListGrpcResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.soa.tour_service.grpc.TourListGrpcResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TourListGrpcResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TourListGrpcResponse)
      com.soa.tour_service.grpc.TourListGrpcResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.soa.tour_service.grpc.TourProto.internal_static_TourListGrpcResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.soa.tour_service.grpc.TourProto.internal_static_TourListGrpcResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.soa.tour_service.grpc.TourListGrpcResponse.class, com.soa.tour_service.grpc.TourListGrpcResponse.Builder.class);
    }

    // Construct using com.soa.tour_service.grpc.TourListGrpcResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getToursFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (toursBuilder_ == null) {
        tours_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        toursBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.soa.tour_service.grpc.TourProto.internal_static_TourListGrpcResponse_descriptor;
    }

    @java.lang.Override
    public com.soa.tour_service.grpc.TourListGrpcResponse getDefaultInstanceForType() {
      return com.soa.tour_service.grpc.TourListGrpcResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.soa.tour_service.grpc.TourListGrpcResponse build() {
      com.soa.tour_service.grpc.TourListGrpcResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.soa.tour_service.grpc.TourListGrpcResponse buildPartial() {
      com.soa.tour_service.grpc.TourListGrpcResponse result = new com.soa.tour_service.grpc.TourListGrpcResponse(this);
      int from_bitField0_ = bitField0_;
      if (toursBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          tours_ = java.util.Collections.unmodifiableList(tours_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.tours_ = tours_;
      } else {
        result.tours_ = toursBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.soa.tour_service.grpc.TourListGrpcResponse) {
        return mergeFrom((com.soa.tour_service.grpc.TourListGrpcResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.soa.tour_service.grpc.TourListGrpcResponse other) {
      if (other == com.soa.tour_service.grpc.TourListGrpcResponse.getDefaultInstance()) return this;
      if (toursBuilder_ == null) {
        if (!other.tours_.isEmpty()) {
          if (tours_.isEmpty()) {
            tours_ = other.tours_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureToursIsMutable();
            tours_.addAll(other.tours_);
          }
          onChanged();
        }
      } else {
        if (!other.tours_.isEmpty()) {
          if (toursBuilder_.isEmpty()) {
            toursBuilder_.dispose();
            toursBuilder_ = null;
            tours_ = other.tours_;
            bitField0_ = (bitField0_ & ~0x00000001);
            toursBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getToursFieldBuilder() : null;
          } else {
            toursBuilder_.addAllMessages(other.tours_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.soa.tour_service.grpc.TourListGrpcResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.soa.tour_service.grpc.TourListGrpcResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.soa.tour_service.grpc.TourGrpcResponse> tours_ =
      java.util.Collections.emptyList();
    private void ensureToursIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        tours_ = new java.util.ArrayList<com.soa.tour_service.grpc.TourGrpcResponse>(tours_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.soa.tour_service.grpc.TourGrpcResponse, com.soa.tour_service.grpc.TourGrpcResponse.Builder, com.soa.tour_service.grpc.TourGrpcResponseOrBuilder> toursBuilder_;

    /**
     * <code>repeated .TourGrpcResponse tours = 1;</code>
     */
    public java.util.List<com.soa.tour_service.grpc.TourGrpcResponse> getToursList() {
      if (toursBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tours_);
      } else {
        return toursBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .TourGrpcResponse tours = 1;</code>
     */
    public int getToursCount() {
      if (toursBuilder_ == null) {
        return tours_.size();
      } else {
        return toursBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .TourGrpcResponse tours = 1;</code>
     */
    public com.soa.tour_service.grpc.TourGrpcResponse getTours(int index) {
      if (toursBuilder_ == null) {
        return tours_.get(index);
      } else {
        return toursBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .TourGrpcResponse tours = 1;</code>
     */
    public Builder setTours(
        int index, com.soa.tour_service.grpc.TourGrpcResponse value) {
      if (toursBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureToursIsMutable();
        tours_.set(index, value);
        onChanged();
      } else {
        toursBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TourGrpcResponse tours = 1;</code>
     */
    public Builder setTours(
        int index, com.soa.tour_service.grpc.TourGrpcResponse.Builder builderForValue) {
      if (toursBuilder_ == null) {
        ensureToursIsMutable();
        tours_.set(index, builderForValue.build());
        onChanged();
      } else {
        toursBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TourGrpcResponse tours = 1;</code>
     */
    public Builder addTours(com.soa.tour_service.grpc.TourGrpcResponse value) {
      if (toursBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureToursIsMutable();
        tours_.add(value);
        onChanged();
      } else {
        toursBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .TourGrpcResponse tours = 1;</code>
     */
    public Builder addTours(
        int index, com.soa.tour_service.grpc.TourGrpcResponse value) {
      if (toursBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureToursIsMutable();
        tours_.add(index, value);
        onChanged();
      } else {
        toursBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TourGrpcResponse tours = 1;</code>
     */
    public Builder addTours(
        com.soa.tour_service.grpc.TourGrpcResponse.Builder builderForValue) {
      if (toursBuilder_ == null) {
        ensureToursIsMutable();
        tours_.add(builderForValue.build());
        onChanged();
      } else {
        toursBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TourGrpcResponse tours = 1;</code>
     */
    public Builder addTours(
        int index, com.soa.tour_service.grpc.TourGrpcResponse.Builder builderForValue) {
      if (toursBuilder_ == null) {
        ensureToursIsMutable();
        tours_.add(index, builderForValue.build());
        onChanged();
      } else {
        toursBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TourGrpcResponse tours = 1;</code>
     */
    public Builder addAllTours(
        java.lang.Iterable<? extends com.soa.tour_service.grpc.TourGrpcResponse> values) {
      if (toursBuilder_ == null) {
        ensureToursIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tours_);
        onChanged();
      } else {
        toursBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .TourGrpcResponse tours = 1;</code>
     */
    public Builder clearTours() {
      if (toursBuilder_ == null) {
        tours_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        toursBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .TourGrpcResponse tours = 1;</code>
     */
    public Builder removeTours(int index) {
      if (toursBuilder_ == null) {
        ensureToursIsMutable();
        tours_.remove(index);
        onChanged();
      } else {
        toursBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .TourGrpcResponse tours = 1;</code>
     */
    public com.soa.tour_service.grpc.TourGrpcResponse.Builder getToursBuilder(
        int index) {
      return getToursFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .TourGrpcResponse tours = 1;</code>
     */
    public com.soa.tour_service.grpc.TourGrpcResponseOrBuilder getToursOrBuilder(
        int index) {
      if (toursBuilder_ == null) {
        return tours_.get(index);  } else {
        return toursBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .TourGrpcResponse tours = 1;</code>
     */
    public java.util.List<? extends com.soa.tour_service.grpc.TourGrpcResponseOrBuilder> 
         getToursOrBuilderList() {
      if (toursBuilder_ != null) {
        return toursBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tours_);
      }
    }
    /**
     * <code>repeated .TourGrpcResponse tours = 1;</code>
     */
    public com.soa.tour_service.grpc.TourGrpcResponse.Builder addToursBuilder() {
      return getToursFieldBuilder().addBuilder(
          com.soa.tour_service.grpc.TourGrpcResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .TourGrpcResponse tours = 1;</code>
     */
    public com.soa.tour_service.grpc.TourGrpcResponse.Builder addToursBuilder(
        int index) {
      return getToursFieldBuilder().addBuilder(
          index, com.soa.tour_service.grpc.TourGrpcResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .TourGrpcResponse tours = 1;</code>
     */
    public java.util.List<com.soa.tour_service.grpc.TourGrpcResponse.Builder> 
         getToursBuilderList() {
      return getToursFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.soa.tour_service.grpc.TourGrpcResponse, com.soa.tour_service.grpc.TourGrpcResponse.Builder, com.soa.tour_service.grpc.TourGrpcResponseOrBuilder> 
        getToursFieldBuilder() {
      if (toursBuilder_ == null) {
        toursBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.soa.tour_service.grpc.TourGrpcResponse, com.soa.tour_service.grpc.TourGrpcResponse.Builder, com.soa.tour_service.grpc.TourGrpcResponseOrBuilder>(
                tours_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        tours_ = null;
      }
      return toursBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TourListGrpcResponse)
  }

  // @@protoc_insertion_point(class_scope:TourListGrpcResponse)
  private static final com.soa.tour_service.grpc.TourListGrpcResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.soa.tour_service.grpc.TourListGrpcResponse();
  }

  public static com.soa.tour_service.grpc.TourListGrpcResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TourListGrpcResponse>
      PARSER = new com.google.protobuf.AbstractParser<TourListGrpcResponse>() {
    @java.lang.Override
    public TourListGrpcResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TourListGrpcResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TourListGrpcResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TourListGrpcResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.soa.tour_service.grpc.TourListGrpcResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

