// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tour.proto

package com.soa.tour_service.grpc;

/**
 * Protobuf type {@code TourTransportTimeGrpcResponse}
 */
public  final class TourTransportTimeGrpcResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TourTransportTimeGrpcResponse)
    TourTransportTimeGrpcResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TourTransportTimeGrpcResponse.newBuilder() to construct.
  private TourTransportTimeGrpcResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TourTransportTimeGrpcResponse() {
    transportType_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TourTransportTimeGrpcResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TourTransportTimeGrpcResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            transportType_ = s;
            break;
          }
          case 24: {

            durationMinutes_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.soa.tour_service.grpc.TourProto.internal_static_TourTransportTimeGrpcResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.soa.tour_service.grpc.TourProto.internal_static_TourTransportTimeGrpcResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.soa.tour_service.grpc.TourTransportTimeGrpcResponse.class, com.soa.tour_service.grpc.TourTransportTimeGrpcResponse.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  public long getId() {
    return id_;
  }

  public static final int TRANSPORTTYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object transportType_;
  /**
   * <code>string transportType = 2;</code>
   * @return The transportType.
   */
  public java.lang.String getTransportType() {
    java.lang.Object ref = transportType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transportType_ = s;
      return s;
    }
  }
  /**
   * <code>string transportType = 2;</code>
   * @return The bytes for transportType.
   */
  public com.google.protobuf.ByteString
      getTransportTypeBytes() {
    java.lang.Object ref = transportType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transportType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DURATIONMINUTES_FIELD_NUMBER = 3;
  private int durationMinutes_;
  /**
   * <code>int32 durationMinutes = 3;</code>
   * @return The durationMinutes.
   */
  public int getDurationMinutes() {
    return durationMinutes_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getTransportTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, transportType_);
    }
    if (durationMinutes_ != 0) {
      output.writeInt32(3, durationMinutes_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getTransportTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, transportType_);
    }
    if (durationMinutes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, durationMinutes_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.soa.tour_service.grpc.TourTransportTimeGrpcResponse)) {
      return super.equals(obj);
    }
    com.soa.tour_service.grpc.TourTransportTimeGrpcResponse other = (com.soa.tour_service.grpc.TourTransportTimeGrpcResponse) obj;

    if (getId()
        != other.getId()) return false;
    if (!getTransportType()
        .equals(other.getTransportType())) return false;
    if (getDurationMinutes()
        != other.getDurationMinutes()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + TRANSPORTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getTransportType().hashCode();
    hash = (37 * hash) + DURATIONMINUTES_FIELD_NUMBER;
    hash = (53 * hash) + getDurationMinutes();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.soa.tour_service.grpc.TourTransportTimeGrpcResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.soa.tour_service.grpc.TourTransportTimeGrpcResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.soa.tour_service.grpc.TourTransportTimeGrpcResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.soa.tour_service.grpc.TourTransportTimeGrpcResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.soa.tour_service.grpc.TourTransportTimeGrpcResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.soa.tour_service.grpc.TourTransportTimeGrpcResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.soa.tour_service.grpc.TourTransportTimeGrpcResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.soa.tour_service.grpc.TourTransportTimeGrpcResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.soa.tour_service.grpc.TourTransportTimeGrpcResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.soa.tour_service.grpc.TourTransportTimeGrpcResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.soa.tour_service.grpc.TourTransportTimeGrpcResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.soa.tour_service.grpc.TourTransportTimeGrpcResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.soa.tour_service.grpc.TourTransportTimeGrpcResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TourTransportTimeGrpcResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TourTransportTimeGrpcResponse)
      com.soa.tour_service.grpc.TourTransportTimeGrpcResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.soa.tour_service.grpc.TourProto.internal_static_TourTransportTimeGrpcResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.soa.tour_service.grpc.TourProto.internal_static_TourTransportTimeGrpcResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.soa.tour_service.grpc.TourTransportTimeGrpcResponse.class, com.soa.tour_service.grpc.TourTransportTimeGrpcResponse.Builder.class);
    }

    // Construct using com.soa.tour_service.grpc.TourTransportTimeGrpcResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      transportType_ = "";

      durationMinutes_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.soa.tour_service.grpc.TourProto.internal_static_TourTransportTimeGrpcResponse_descriptor;
    }

    @java.lang.Override
    public com.soa.tour_service.grpc.TourTransportTimeGrpcResponse getDefaultInstanceForType() {
      return com.soa.tour_service.grpc.TourTransportTimeGrpcResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.soa.tour_service.grpc.TourTransportTimeGrpcResponse build() {
      com.soa.tour_service.grpc.TourTransportTimeGrpcResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.soa.tour_service.grpc.TourTransportTimeGrpcResponse buildPartial() {
      com.soa.tour_service.grpc.TourTransportTimeGrpcResponse result = new com.soa.tour_service.grpc.TourTransportTimeGrpcResponse(this);
      result.id_ = id_;
      result.transportType_ = transportType_;
      result.durationMinutes_ = durationMinutes_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.soa.tour_service.grpc.TourTransportTimeGrpcResponse) {
        return mergeFrom((com.soa.tour_service.grpc.TourTransportTimeGrpcResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.soa.tour_service.grpc.TourTransportTimeGrpcResponse other) {
      if (other == com.soa.tour_service.grpc.TourTransportTimeGrpcResponse.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getTransportType().isEmpty()) {
        transportType_ = other.transportType_;
        onChanged();
      }
      if (other.getDurationMinutes() != 0) {
        setDurationMinutes(other.getDurationMinutes());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.soa.tour_service.grpc.TourTransportTimeGrpcResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.soa.tour_service.grpc.TourTransportTimeGrpcResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object transportType_ = "";
    /**
     * <code>string transportType = 2;</code>
     * @return The transportType.
     */
    public java.lang.String getTransportType() {
      java.lang.Object ref = transportType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transportType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transportType = 2;</code>
     * @return The bytes for transportType.
     */
    public com.google.protobuf.ByteString
        getTransportTypeBytes() {
      java.lang.Object ref = transportType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transportType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transportType = 2;</code>
     * @param value The transportType to set.
     * @return This builder for chaining.
     */
    public Builder setTransportType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transportType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string transportType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransportType() {
      
      transportType_ = getDefaultInstance().getTransportType();
      onChanged();
      return this;
    }
    /**
     * <code>string transportType = 2;</code>
     * @param value The bytes for transportType to set.
     * @return This builder for chaining.
     */
    public Builder setTransportTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transportType_ = value;
      onChanged();
      return this;
    }

    private int durationMinutes_ ;
    /**
     * <code>int32 durationMinutes = 3;</code>
     * @return The durationMinutes.
     */
    public int getDurationMinutes() {
      return durationMinutes_;
    }
    /**
     * <code>int32 durationMinutes = 3;</code>
     * @param value The durationMinutes to set.
     * @return This builder for chaining.
     */
    public Builder setDurationMinutes(int value) {
      
      durationMinutes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 durationMinutes = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDurationMinutes() {
      
      durationMinutes_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TourTransportTimeGrpcResponse)
  }

  // @@protoc_insertion_point(class_scope:TourTransportTimeGrpcResponse)
  private static final com.soa.tour_service.grpc.TourTransportTimeGrpcResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.soa.tour_service.grpc.TourTransportTimeGrpcResponse();
  }

  public static com.soa.tour_service.grpc.TourTransportTimeGrpcResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TourTransportTimeGrpcResponse>
      PARSER = new com.google.protobuf.AbstractParser<TourTransportTimeGrpcResponse>() {
    @java.lang.Override
    public TourTransportTimeGrpcResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TourTransportTimeGrpcResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TourTransportTimeGrpcResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TourTransportTimeGrpcResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.soa.tour_service.grpc.TourTransportTimeGrpcResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

