// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tour.proto

package com.soa.tour_service.grpc;

/**
 * Protobuf type {@code TourGrpcResponse}
 */
public  final class TourGrpcResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TourGrpcResponse)
    TourGrpcResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TourGrpcResponse.newBuilder() to construct.
  private TourGrpcResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TourGrpcResponse() {
    name_ = "";
    description_ = "";
    difficulty_ = "";
    status_ = "";
    transportTimes_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TourGrpcResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TourGrpcResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            difficulty_ = s;
            break;
          }
          case 41: {

            price_ = input.readDouble();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            status_ = s;
            break;
          }
          case 56: {

            authorId_ = input.readInt64();
            break;
          }
          case 65: {

            distanceInKm_ = input.readDouble();
            break;
          }
          case 74: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              transportTimes_ = new java.util.ArrayList<com.soa.tour_service.grpc.TourTransportTimeGrpcResponse>();
              mutable_bitField0_ |= 0x00000001;
            }
            transportTimes_.add(
                input.readMessage(com.soa.tour_service.grpc.TourTransportTimeGrpcResponse.parser(), extensionRegistry));
            break;
          }
          case 80: {

            inShoppingCart_ = input.readBool();
            break;
          }
          case 88: {

            purchased_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        transportTimes_ = java.util.Collections.unmodifiableList(transportTimes_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.soa.tour_service.grpc.TourProto.internal_static_TourGrpcResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.soa.tour_service.grpc.TourProto.internal_static_TourGrpcResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.soa.tour_service.grpc.TourGrpcResponse.class, com.soa.tour_service.grpc.TourGrpcResponse.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  public long getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIFFICULTY_FIELD_NUMBER = 4;
  private volatile java.lang.Object difficulty_;
  /**
   * <code>string difficulty = 4;</code>
   * @return The difficulty.
   */
  public java.lang.String getDifficulty() {
    java.lang.Object ref = difficulty_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      difficulty_ = s;
      return s;
    }
  }
  /**
   * <code>string difficulty = 4;</code>
   * @return The bytes for difficulty.
   */
  public com.google.protobuf.ByteString
      getDifficultyBytes() {
    java.lang.Object ref = difficulty_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      difficulty_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICE_FIELD_NUMBER = 5;
  private double price_;
  /**
   * <code>double price = 5;</code>
   * @return The price.
   */
  public double getPrice() {
    return price_;
  }

  public static final int STATUS_FIELD_NUMBER = 6;
  private volatile java.lang.Object status_;
  /**
   * <code>string status = 6;</code>
   * @return The status.
   */
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 6;</code>
   * @return The bytes for status.
   */
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUTHORID_FIELD_NUMBER = 7;
  private long authorId_;
  /**
   * <code>int64 authorId = 7;</code>
   * @return The authorId.
   */
  public long getAuthorId() {
    return authorId_;
  }

  public static final int DISTANCEINKM_FIELD_NUMBER = 8;
  private double distanceInKm_;
  /**
   * <code>double distanceInKm = 8;</code>
   * @return The distanceInKm.
   */
  public double getDistanceInKm() {
    return distanceInKm_;
  }

  public static final int TRANSPORTTIMES_FIELD_NUMBER = 9;
  private java.util.List<com.soa.tour_service.grpc.TourTransportTimeGrpcResponse> transportTimes_;
  /**
   * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
   */
  public java.util.List<com.soa.tour_service.grpc.TourTransportTimeGrpcResponse> getTransportTimesList() {
    return transportTimes_;
  }
  /**
   * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
   */
  public java.util.List<? extends com.soa.tour_service.grpc.TourTransportTimeGrpcResponseOrBuilder> 
      getTransportTimesOrBuilderList() {
    return transportTimes_;
  }
  /**
   * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
   */
  public int getTransportTimesCount() {
    return transportTimes_.size();
  }
  /**
   * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
   */
  public com.soa.tour_service.grpc.TourTransportTimeGrpcResponse getTransportTimes(int index) {
    return transportTimes_.get(index);
  }
  /**
   * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
   */
  public com.soa.tour_service.grpc.TourTransportTimeGrpcResponseOrBuilder getTransportTimesOrBuilder(
      int index) {
    return transportTimes_.get(index);
  }

  public static final int INSHOPPINGCART_FIELD_NUMBER = 10;
  private boolean inShoppingCart_;
  /**
   * <code>bool inShoppingCart = 10;</code>
   * @return The inShoppingCart.
   */
  public boolean getInShoppingCart() {
    return inShoppingCart_;
  }

  public static final int PURCHASED_FIELD_NUMBER = 11;
  private boolean purchased_;
  /**
   * <code>bool purchased = 11;</code>
   * @return The purchased.
   */
  public boolean getPurchased() {
    return purchased_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
    }
    if (!getDifficultyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, difficulty_);
    }
    if (price_ != 0D) {
      output.writeDouble(5, price_);
    }
    if (!getStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, status_);
    }
    if (authorId_ != 0L) {
      output.writeInt64(7, authorId_);
    }
    if (distanceInKm_ != 0D) {
      output.writeDouble(8, distanceInKm_);
    }
    for (int i = 0; i < transportTimes_.size(); i++) {
      output.writeMessage(9, transportTimes_.get(i));
    }
    if (inShoppingCart_ != false) {
      output.writeBool(10, inShoppingCart_);
    }
    if (purchased_ != false) {
      output.writeBool(11, purchased_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
    }
    if (!getDifficultyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, difficulty_);
    }
    if (price_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, price_);
    }
    if (!getStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, status_);
    }
    if (authorId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, authorId_);
    }
    if (distanceInKm_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, distanceInKm_);
    }
    for (int i = 0; i < transportTimes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, transportTimes_.get(i));
    }
    if (inShoppingCart_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, inShoppingCart_);
    }
    if (purchased_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, purchased_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.soa.tour_service.grpc.TourGrpcResponse)) {
      return super.equals(obj);
    }
    com.soa.tour_service.grpc.TourGrpcResponse other = (com.soa.tour_service.grpc.TourGrpcResponse) obj;

    if (getId()
        != other.getId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getDifficulty()
        .equals(other.getDifficulty())) return false;
    if (java.lang.Double.doubleToLongBits(getPrice())
        != java.lang.Double.doubleToLongBits(
            other.getPrice())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (getAuthorId()
        != other.getAuthorId()) return false;
    if (java.lang.Double.doubleToLongBits(getDistanceInKm())
        != java.lang.Double.doubleToLongBits(
            other.getDistanceInKm())) return false;
    if (!getTransportTimesList()
        .equals(other.getTransportTimesList())) return false;
    if (getInShoppingCart()
        != other.getInShoppingCart()) return false;
    if (getPurchased()
        != other.getPurchased()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + DIFFICULTY_FIELD_NUMBER;
    hash = (53 * hash) + getDifficulty().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPrice()));
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + AUTHORID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAuthorId());
    hash = (37 * hash) + DISTANCEINKM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDistanceInKm()));
    if (getTransportTimesCount() > 0) {
      hash = (37 * hash) + TRANSPORTTIMES_FIELD_NUMBER;
      hash = (53 * hash) + getTransportTimesList().hashCode();
    }
    hash = (37 * hash) + INSHOPPINGCART_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getInShoppingCart());
    hash = (37 * hash) + PURCHASED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPurchased());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.soa.tour_service.grpc.TourGrpcResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.soa.tour_service.grpc.TourGrpcResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.soa.tour_service.grpc.TourGrpcResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.soa.tour_service.grpc.TourGrpcResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.soa.tour_service.grpc.TourGrpcResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.soa.tour_service.grpc.TourGrpcResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.soa.tour_service.grpc.TourGrpcResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.soa.tour_service.grpc.TourGrpcResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.soa.tour_service.grpc.TourGrpcResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.soa.tour_service.grpc.TourGrpcResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.soa.tour_service.grpc.TourGrpcResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.soa.tour_service.grpc.TourGrpcResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.soa.tour_service.grpc.TourGrpcResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TourGrpcResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TourGrpcResponse)
      com.soa.tour_service.grpc.TourGrpcResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.soa.tour_service.grpc.TourProto.internal_static_TourGrpcResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.soa.tour_service.grpc.TourProto.internal_static_TourGrpcResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.soa.tour_service.grpc.TourGrpcResponse.class, com.soa.tour_service.grpc.TourGrpcResponse.Builder.class);
    }

    // Construct using com.soa.tour_service.grpc.TourGrpcResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTransportTimesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      name_ = "";

      description_ = "";

      difficulty_ = "";

      price_ = 0D;

      status_ = "";

      authorId_ = 0L;

      distanceInKm_ = 0D;

      if (transportTimesBuilder_ == null) {
        transportTimes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        transportTimesBuilder_.clear();
      }
      inShoppingCart_ = false;

      purchased_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.soa.tour_service.grpc.TourProto.internal_static_TourGrpcResponse_descriptor;
    }

    @java.lang.Override
    public com.soa.tour_service.grpc.TourGrpcResponse getDefaultInstanceForType() {
      return com.soa.tour_service.grpc.TourGrpcResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.soa.tour_service.grpc.TourGrpcResponse build() {
      com.soa.tour_service.grpc.TourGrpcResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.soa.tour_service.grpc.TourGrpcResponse buildPartial() {
      com.soa.tour_service.grpc.TourGrpcResponse result = new com.soa.tour_service.grpc.TourGrpcResponse(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.name_ = name_;
      result.description_ = description_;
      result.difficulty_ = difficulty_;
      result.price_ = price_;
      result.status_ = status_;
      result.authorId_ = authorId_;
      result.distanceInKm_ = distanceInKm_;
      if (transportTimesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          transportTimes_ = java.util.Collections.unmodifiableList(transportTimes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.transportTimes_ = transportTimes_;
      } else {
        result.transportTimes_ = transportTimesBuilder_.build();
      }
      result.inShoppingCart_ = inShoppingCart_;
      result.purchased_ = purchased_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.soa.tour_service.grpc.TourGrpcResponse) {
        return mergeFrom((com.soa.tour_service.grpc.TourGrpcResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.soa.tour_service.grpc.TourGrpcResponse other) {
      if (other == com.soa.tour_service.grpc.TourGrpcResponse.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.getDifficulty().isEmpty()) {
        difficulty_ = other.difficulty_;
        onChanged();
      }
      if (other.getPrice() != 0D) {
        setPrice(other.getPrice());
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      if (other.getAuthorId() != 0L) {
        setAuthorId(other.getAuthorId());
      }
      if (other.getDistanceInKm() != 0D) {
        setDistanceInKm(other.getDistanceInKm());
      }
      if (transportTimesBuilder_ == null) {
        if (!other.transportTimes_.isEmpty()) {
          if (transportTimes_.isEmpty()) {
            transportTimes_ = other.transportTimes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTransportTimesIsMutable();
            transportTimes_.addAll(other.transportTimes_);
          }
          onChanged();
        }
      } else {
        if (!other.transportTimes_.isEmpty()) {
          if (transportTimesBuilder_.isEmpty()) {
            transportTimesBuilder_.dispose();
            transportTimesBuilder_ = null;
            transportTimes_ = other.transportTimes_;
            bitField0_ = (bitField0_ & ~0x00000001);
            transportTimesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTransportTimesFieldBuilder() : null;
          } else {
            transportTimesBuilder_.addAllMessages(other.transportTimes_);
          }
        }
      }
      if (other.getInShoppingCart() != false) {
        setInShoppingCart(other.getInShoppingCart());
      }
      if (other.getPurchased() != false) {
        setPurchased(other.getPurchased());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.soa.tour_service.grpc.TourGrpcResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.soa.tour_service.grpc.TourGrpcResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object difficulty_ = "";
    /**
     * <code>string difficulty = 4;</code>
     * @return The difficulty.
     */
    public java.lang.String getDifficulty() {
      java.lang.Object ref = difficulty_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        difficulty_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string difficulty = 4;</code>
     * @return The bytes for difficulty.
     */
    public com.google.protobuf.ByteString
        getDifficultyBytes() {
      java.lang.Object ref = difficulty_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        difficulty_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string difficulty = 4;</code>
     * @param value The difficulty to set.
     * @return This builder for chaining.
     */
    public Builder setDifficulty(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      difficulty_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string difficulty = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDifficulty() {
      
      difficulty_ = getDefaultInstance().getDifficulty();
      onChanged();
      return this;
    }
    /**
     * <code>string difficulty = 4;</code>
     * @param value The bytes for difficulty to set.
     * @return This builder for chaining.
     */
    public Builder setDifficultyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      difficulty_ = value;
      onChanged();
      return this;
    }

    private double price_ ;
    /**
     * <code>double price = 5;</code>
     * @return The price.
     */
    public double getPrice() {
      return price_;
    }
    /**
     * <code>double price = 5;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(double value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double price = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      
      price_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 6;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 6;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 6;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string status = 6;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      status_ = value;
      onChanged();
      return this;
    }

    private long authorId_ ;
    /**
     * <code>int64 authorId = 7;</code>
     * @return The authorId.
     */
    public long getAuthorId() {
      return authorId_;
    }
    /**
     * <code>int64 authorId = 7;</code>
     * @param value The authorId to set.
     * @return This builder for chaining.
     */
    public Builder setAuthorId(long value) {
      
      authorId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 authorId = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthorId() {
      
      authorId_ = 0L;
      onChanged();
      return this;
    }

    private double distanceInKm_ ;
    /**
     * <code>double distanceInKm = 8;</code>
     * @return The distanceInKm.
     */
    public double getDistanceInKm() {
      return distanceInKm_;
    }
    /**
     * <code>double distanceInKm = 8;</code>
     * @param value The distanceInKm to set.
     * @return This builder for chaining.
     */
    public Builder setDistanceInKm(double value) {
      
      distanceInKm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double distanceInKm = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDistanceInKm() {
      
      distanceInKm_ = 0D;
      onChanged();
      return this;
    }

    private java.util.List<com.soa.tour_service.grpc.TourTransportTimeGrpcResponse> transportTimes_ =
      java.util.Collections.emptyList();
    private void ensureTransportTimesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        transportTimes_ = new java.util.ArrayList<com.soa.tour_service.grpc.TourTransportTimeGrpcResponse>(transportTimes_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.soa.tour_service.grpc.TourTransportTimeGrpcResponse, com.soa.tour_service.grpc.TourTransportTimeGrpcResponse.Builder, com.soa.tour_service.grpc.TourTransportTimeGrpcResponseOrBuilder> transportTimesBuilder_;

    /**
     * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
     */
    public java.util.List<com.soa.tour_service.grpc.TourTransportTimeGrpcResponse> getTransportTimesList() {
      if (transportTimesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(transportTimes_);
      } else {
        return transportTimesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
     */
    public int getTransportTimesCount() {
      if (transportTimesBuilder_ == null) {
        return transportTimes_.size();
      } else {
        return transportTimesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
     */
    public com.soa.tour_service.grpc.TourTransportTimeGrpcResponse getTransportTimes(int index) {
      if (transportTimesBuilder_ == null) {
        return transportTimes_.get(index);
      } else {
        return transportTimesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
     */
    public Builder setTransportTimes(
        int index, com.soa.tour_service.grpc.TourTransportTimeGrpcResponse value) {
      if (transportTimesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransportTimesIsMutable();
        transportTimes_.set(index, value);
        onChanged();
      } else {
        transportTimesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
     */
    public Builder setTransportTimes(
        int index, com.soa.tour_service.grpc.TourTransportTimeGrpcResponse.Builder builderForValue) {
      if (transportTimesBuilder_ == null) {
        ensureTransportTimesIsMutable();
        transportTimes_.set(index, builderForValue.build());
        onChanged();
      } else {
        transportTimesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
     */
    public Builder addTransportTimes(com.soa.tour_service.grpc.TourTransportTimeGrpcResponse value) {
      if (transportTimesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransportTimesIsMutable();
        transportTimes_.add(value);
        onChanged();
      } else {
        transportTimesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
     */
    public Builder addTransportTimes(
        int index, com.soa.tour_service.grpc.TourTransportTimeGrpcResponse value) {
      if (transportTimesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransportTimesIsMutable();
        transportTimes_.add(index, value);
        onChanged();
      } else {
        transportTimesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
     */
    public Builder addTransportTimes(
        com.soa.tour_service.grpc.TourTransportTimeGrpcResponse.Builder builderForValue) {
      if (transportTimesBuilder_ == null) {
        ensureTransportTimesIsMutable();
        transportTimes_.add(builderForValue.build());
        onChanged();
      } else {
        transportTimesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
     */
    public Builder addTransportTimes(
        int index, com.soa.tour_service.grpc.TourTransportTimeGrpcResponse.Builder builderForValue) {
      if (transportTimesBuilder_ == null) {
        ensureTransportTimesIsMutable();
        transportTimes_.add(index, builderForValue.build());
        onChanged();
      } else {
        transportTimesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
     */
    public Builder addAllTransportTimes(
        java.lang.Iterable<? extends com.soa.tour_service.grpc.TourTransportTimeGrpcResponse> values) {
      if (transportTimesBuilder_ == null) {
        ensureTransportTimesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, transportTimes_);
        onChanged();
      } else {
        transportTimesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
     */
    public Builder clearTransportTimes() {
      if (transportTimesBuilder_ == null) {
        transportTimes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        transportTimesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
     */
    public Builder removeTransportTimes(int index) {
      if (transportTimesBuilder_ == null) {
        ensureTransportTimesIsMutable();
        transportTimes_.remove(index);
        onChanged();
      } else {
        transportTimesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
     */
    public com.soa.tour_service.grpc.TourTransportTimeGrpcResponse.Builder getTransportTimesBuilder(
        int index) {
      return getTransportTimesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
     */
    public com.soa.tour_service.grpc.TourTransportTimeGrpcResponseOrBuilder getTransportTimesOrBuilder(
        int index) {
      if (transportTimesBuilder_ == null) {
        return transportTimes_.get(index);  } else {
        return transportTimesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
     */
    public java.util.List<? extends com.soa.tour_service.grpc.TourTransportTimeGrpcResponseOrBuilder> 
         getTransportTimesOrBuilderList() {
      if (transportTimesBuilder_ != null) {
        return transportTimesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(transportTimes_);
      }
    }
    /**
     * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
     */
    public com.soa.tour_service.grpc.TourTransportTimeGrpcResponse.Builder addTransportTimesBuilder() {
      return getTransportTimesFieldBuilder().addBuilder(
          com.soa.tour_service.grpc.TourTransportTimeGrpcResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
     */
    public com.soa.tour_service.grpc.TourTransportTimeGrpcResponse.Builder addTransportTimesBuilder(
        int index) {
      return getTransportTimesFieldBuilder().addBuilder(
          index, com.soa.tour_service.grpc.TourTransportTimeGrpcResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .TourTransportTimeGrpcResponse transportTimes = 9;</code>
     */
    public java.util.List<com.soa.tour_service.grpc.TourTransportTimeGrpcResponse.Builder> 
         getTransportTimesBuilderList() {
      return getTransportTimesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.soa.tour_service.grpc.TourTransportTimeGrpcResponse, com.soa.tour_service.grpc.TourTransportTimeGrpcResponse.Builder, com.soa.tour_service.grpc.TourTransportTimeGrpcResponseOrBuilder> 
        getTransportTimesFieldBuilder() {
      if (transportTimesBuilder_ == null) {
        transportTimesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.soa.tour_service.grpc.TourTransportTimeGrpcResponse, com.soa.tour_service.grpc.TourTransportTimeGrpcResponse.Builder, com.soa.tour_service.grpc.TourTransportTimeGrpcResponseOrBuilder>(
                transportTimes_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        transportTimes_ = null;
      }
      return transportTimesBuilder_;
    }

    private boolean inShoppingCart_ ;
    /**
     * <code>bool inShoppingCart = 10;</code>
     * @return The inShoppingCart.
     */
    public boolean getInShoppingCart() {
      return inShoppingCart_;
    }
    /**
     * <code>bool inShoppingCart = 10;</code>
     * @param value The inShoppingCart to set.
     * @return This builder for chaining.
     */
    public Builder setInShoppingCart(boolean value) {
      
      inShoppingCart_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool inShoppingCart = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearInShoppingCart() {
      
      inShoppingCart_ = false;
      onChanged();
      return this;
    }

    private boolean purchased_ ;
    /**
     * <code>bool purchased = 11;</code>
     * @return The purchased.
     */
    public boolean getPurchased() {
      return purchased_;
    }
    /**
     * <code>bool purchased = 11;</code>
     * @param value The purchased to set.
     * @return This builder for chaining.
     */
    public Builder setPurchased(boolean value) {
      
      purchased_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool purchased = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearPurchased() {
      
      purchased_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TourGrpcResponse)
  }

  // @@protoc_insertion_point(class_scope:TourGrpcResponse)
  private static final com.soa.tour_service.grpc.TourGrpcResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.soa.tour_service.grpc.TourGrpcResponse();
  }

  public static com.soa.tour_service.grpc.TourGrpcResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TourGrpcResponse>
      PARSER = new com.google.protobuf.AbstractParser<TourGrpcResponse>() {
    @java.lang.Override
    public TourGrpcResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TourGrpcResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TourGrpcResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TourGrpcResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.soa.tour_service.grpc.TourGrpcResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

