// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tour.proto

package com.soa.tour_service.grpc;

public interface TourTransportTimeGrpcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TourTransportTimeGrpcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string transportType = 2;</code>
   * @return The transportType.
   */
  java.lang.String getTransportType();
  /**
   * <code>string transportType = 2;</code>
   * @return The bytes for transportType.
   */
  com.google.protobuf.ByteString
      getTransportTypeBytes();

  /**
   * <code>int32 durationMinutes = 3;</code>
   * @return The durationMinutes.
   */
  int getDurationMinutes();
}
